gemfile:
  - Gemfile
  - gemfiles/rails3_0.gemfile
  - gemfiles/rails3_1.gemfile
language: ruby
rvm:
  - 1.8.7
  - ree
  - 1.9.3
  - 2.0.0
  - jruby-19mode
notifications:
  email: false
bundler_args: --without development
services: mongodb
